services:
  db:
    image: postgres:15-alpine
    container_name: subwatch_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - subwatch_network

#  app:
#    build: .
#    container_name: subwatch_app
#    restart: always
#    env_file:
#      - .env
#    environment:
#      DB_HOST: db
#      DATABASE_URL: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
#      ASYNC_DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
#    ports:
#      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
#    depends_on:
#      db:
#        condition: service_healthy
#    networks:
#      - subwatch_network
#
networks:
  subwatch_network:
    driver: bridge

volumes:
  db_data: